[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.31.1"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
launchpad = "FMc58Fuua7us6ymQn4GqrNJPhyV1HvAtGbEeRGj7s2m7"
marketplace = "FMc58Fuua7us6ymQn4GqrNJPhyV1HvAtGbEeRGj7s2m7"
token_factory = "FMc58Fuua7us6ymQn4GqrNJPhyV1HvAtGbEeRGj7s2m7"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" 